spring.application.name=movie

server.port=8080
server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://localhost:3307/movie
spring.datasource.username=root
spring.datasource.password=abc123


# JWT Settings
jwt.secret=dU5NhVmbXKx9oZGTQ7ARHU8/47F1cgJcregPvg3sRXy2kFcZpAfN0E+Bea2xATrpNIAQPMNK0mII5eEOOiQaWA==
jwt.expiration-in-ms=86400000