spring.application.name=movie

server.port=8080
server.address=0.0.0.0

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/cineSync}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# CORS Configuration
cors.allowed-origins=http://localhost:5173,http://localhost:8080

# Logging
logging.level.org.example.mason.movie.service=DEBUG

# JWT Settings
jwt.secret=${JWT_SECRET}
jwt.expiration-in-ms=86400000

# TMDB API Configuration
tmdb.api.key=${TMDB_API_KEY}
tmdb.api.base-url=${TMDB_API_BASE_URL:https://api.themoviedb.org/3}